### ISSUE TITLE
Document HMAC signing

### ISSUE THREAD

**Issue by rgee0** [openfaas/docs#102]
`--sign` and `--key` were introduced in openfaas/faas-cli#530.

These should be described, perhaps in an invoke section, under the CLI

**Comment by alexellis** [comment]
@rgee0 what is the status of this issue?

**Comment by rgee0** [comment]
@alexellis the issue is currently open.  A lot of the detail could be lifted from the [workshop](https://github.com/openfaas/workshop/blob/401cdc27cc9945839b9021c6a3a72267f7ca4cac/lab11.md) and made to be more documentation-like.

A possible candidate for a new-contributor.
