### ISSUE TITLE
ACME (letsencryt) API is version 02 now

### ISSUE THREAD

**Issue by diddledan** [openfaas/docs#115]
## Proposed change
The letsencrypt documentation at `docs/docs/reference/ssl/kubernetes-with-cert-manager.md` has the API version of acme set at `01`. This needs to be updated to `02` for futureproofing.

## Context
When you run `kubectl -n openfaas describe issuer/letsencrypt-prod` you receive the following message:

```plain
Status:
  Conditions:
    Last Transition Time:  2019-01-17T13:17:20Z
    Message:               Your ACME server URL is set to a v1 endpoint (https://acme-v01.api.letsencrypt.org/directory). You should update the spec.acme.server field to "https://acme-v02.api.letsencrypt.org/directory"
    Reason:                InvalidConfig
    Status:                False
    Type:                  Ready
```

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.8.3

* Docker version `docker version` (e.g. Docker 17.0.05 ): unsure - GKE version v1.11.5-gke.5

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Kubernetes on Google Cloud

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

**Comment by LucasRoesler** [comment]
I think we should update it, it should just be a matter of incrementing and testing it.

**Comment by alexellis** [comment]
Daniel can you take this please?

**Comment by diddledan** [comment]
Yup, I'll get this into a PR shortly :-)
