### ISSUE TITLE
Broken link from kubernetes setup to the ssl guide

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/docs#118]
On https://docs.openfaas.com/deployment/kubernetes/#deploy-with-ssl the link `Using nginx-ingress and cert-manager` is a dead link because it points to  `https://docs.openfaas.com/reference/ssl/kubernetes-with-cert-manager.md`
## Proposed change

Update the link `Using nginx-ingress and cert-manager` to point to  `https://docs.openfaas.com/reference/ssl/kubernetes-with-cert-manager/`

## Context

This was reported as a dead link in Slack

**Comment by LucasRoesler** [comment]
The docs seem to suggest that it can https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages handle these links

**Comment by alexellis** [comment]
What did we get wrong? I was squinting to see a typo
