### ISSUE TITLE
Document how to use image pull policy for faas-netes

### ISSUE THREAD

**Issue by milsonian** [openfaas/docs#14]
This still needs to be done, opening so I don't lose track of it.

**Comment by alexellis** [comment]
Thanks @milsonian - this is 2 months old now, please can you give an ETA on when you can work on it?

**Comment by alexellis** [comment]
@LucasRoesler maybe it would be best if you took over this task which appears to have been dropped?

**Comment by LucasRoesler** [comment]
Sure, is this just updating the docs or a readme?  Not a lot of details here

**Comment by alexellis** [comment]
Docs I think 👍
