### ISSUE TITLE
Fix cert-manager installation instructions

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/docs#146]
## Proposed change

Update the cert-manager install instructions to match the last instructions from the cert-manager project.

## Context

The current installation breaks with the following error message 

```sh
helm install  --name cert-manager  --namespace kube-system  stable/cert-manager 
failed the first time with the following error: 
validation failed: [unable to recognize "": no matches for kind "Certificate" in vers ....
```

because there were breaking changes from version 0.5 to 0.6 and to 0.7.  This was reported in slack and the upstream issue is here https://github.com/jetstack/cert-manager/issues/1255  Per the ticket in cert-manager , the current instructions can be used, but you must pin the cert-manger version to `0.5.2`

**Comment by alexellis** [comment]
Thanks @LucasRoesler
