### ISSUE TITLE
Add ToC page on Service mesh

### ISSUE THREAD

**Issue by alexellis** [openfaas/docs#152]
## Proposed change

Add ToC page on Service mesh

## Context

Include direct links to the work of @stefanprodan and @matipan 

https://github.com/stefanprodan/istio-gke

https://github.com/openfaas-incubator/openfaas-linkerd2

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
How about adding this under Tutorials -> Featured? We can also add a very brief note on what adding this tech may add. For instance mTLS with Linkerd2

**Comment by matipan** [comment]
On it
