### ISSUE TITLE
Add token to faas-cli docs

### ISSUE THREAD

**Issue by ivanayov** [openfaas/docs#161]
`faas-cli` supports `--token` flag since [#faas-cli/pull/649](https://github.com/openfaas/faas-cli/pull/649) which is missing in the CLI docs

**Comment by alexellis** [comment]
Good catch Ivana

Please can you share which commands are missing it?

**Comment by alexellis** [comment]
@viveksyngh please could you pick this up?

**Comment by viveksyngh** [comment]
Yup I will work on this.

**Comment by viveksyngh** [comment]
we already mentioned about the `--token` flag on the oauth section https://docs.openfaas.com/reference/authentication/ .. do we need to mention inside CLI section separately ?

**Comment by alexellis** [comment]
I don't know. Ivana since you mentioned this, wdyt?

**Comment by alexellis** [comment]
Closing because of @viveksyngh's comment
