### ISSUE TITLE
Update to cert-manager 0.8.0 for SSL page

### ISSUE THREAD

**Issue by alexellis** [openfaas/docs#165]
## Proposed change

Update to cert-manager 0.8.0

Full end to end testing will be required.

Be careful to see all the upgrade notes: https://docs.cert-manager.io/en/latest/tasks/upgrading/upgrading-0.7-0.8.html

## Context

I had an email from LetsEncrypt saying that versions < 0.8.0 will be deprecated and blocked by LetsEncrypt from November.

Here is the web version: https://community.letsencrypt.org/t/blocking-old-cert-manager-versions/98753

## Your Environment

Kubernetes

**Comment by alexellis** [comment]
Some folks at Rancher ran into a few issues, to be noted: https://github.com/jetstack/cert-manager/issues/1983

**Comment by rajibmitra** [comment]
I would love to work on this if not done already by this above commit.

**Comment by alexellis** [comment]
Also needed for OpenFaaS Cloud - https://github.com/openfaas-incubator/ofc-bootstrap/issues/122

**Comment by matipan** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Thanks for the assist @rajibmitra, we needed slightly more changes and have been able to chase the latest version 0.10.0 - please all take a look at the patch.

This was too urgent to leave unattended.

Alex
