### ISSUE TITLE
Update docs to use cert-manager 0.11.0

### ISSUE THREAD

**Issue by alexellis** [openfaas/docs#185]
## Proposed change

Update docs to use cert-manager 0.11.0 to keep up to date.

https://docs.cert-manager.io/en/release-0.11/

## Context

This version has breaking changes in the annotations used and how issuers work.

## Your Environment

Kubernetes 1.15 / 1.16

See how with [Upgrading from v0.10 to v0.11](https://docs.cert-manager.io/en/release-0.11/tasks/upgrading/upgrading-0.10-0.11.html)

**Comment by Waterdrips** [comment]
Ill take a look at this.
