### ISSUE TITLE
Clarify required structure of the 'handler'

### ISSUE THREAD

**Issue by yehoshuadimarsky** [openfaas/docs#203]
## Proposed change

As a newcomer to OpenFaaS, I'm surprised how difficult it is to find an answer to a very simple and core question - what are the minimum requirements for the code that goes in the `handler` argument in the YAML? 

All I see in the docs is that it must be a folder, not a file. Ok. And then it gives examples in Python, Node, etc. Great. But what about for other languages I'm working with (like C#)? (Yes, I know there's a .Net Core template, I already looked at it.) 

So the user is left to _assume_, without _any_ confirmation, that the only requirement is that there be some function named `handle` that accepts a single argument of type `string` and either returns a `string` or writes to STDOUT. 

**Is this true? Why is this not clearly stated in the docs?**

For comparison, the Azure Functions docs clearly state the requirements and structure of all the components of the Function, [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python) is the Python part of the docs.

**Comment by alexellis** [comment]
Hi, thanks for your feedback, we'll take a look into this. 

For technical support, please feel free to use Slack and general Q&A. https://slack.openfaas.io/

**Comment by alexellis** [comment]
If your primary use-case is C#, then please feel free to check out the source code for the template you are using. 

For triggers, see the docs page on events and triggers -> https://docs.openfaas.com/reference/triggers/

For the other templates available in the Function Store, try `faas-cli store list`, note that not all of the templates are provided by the project.

Some more notes on templates from the docs:
https://docs.openfaas.com/cli/templates/

And the GitHub repository for the original / legacy templates:
https://github.com/openfaas/templates

In general, the templates do not use dynamic binding or "reflection", so if for instance a `string` response is not appropriate, you can use a different template which uses HTTP, or use JSON.

To understand what's available in environmental variables and so forth, see the workshop, which you should be able to "translate" conceptually for C# https://docs.openfaas.com/tutorials/workshop/

**Comment by alexellis** [comment]
```
As a newcomer to OpenFaaS, I'm surprised how difficult it is to find an answer to a very simple and core question - what are the minimum requirements for the code that goes in the handler argument in the YAML?
```

The handler field is documented here, https://docs.openfaas.com/reference/yaml/#function-handler

> The function handler field refers to a folder where the function's source code can be found, it must always be a folder and not a filename. 

```
All I see in the docs is that it must be a folder, not a file. Ok. And then it gives examples in Python, Node, etc. Great. But what about for other languages I'm working with (like C#)? (Yes, I know there's a .Net Core template, I already looked at it.)
```

You'll need to be more specific about what you're looking for so, that we can point you at the right resource, as I mentioned before, Slack is the best resource for this kind of technical support, Slack and the workshop.

```
So the user is left to assume, without any confirmation, that the only requirement is that there be some function named handle that accepts a single argument of type string and either returns a string or writes to STDOUT.

Is this true? Why is this not clearly stated in the docs?
```

No it's not true. Look up the docs on the watchdog, and read the link about templates, they explain that this is not the case.

https://docs.openfaas.com/cli/templates/

https://docs.openfaas.com/architecture/watchdog/

```
For comparison, the Azure Functions docs clearly state the requirements and structure of all the components of the Function, here is the Python part of the docs.
```

Thanks for the links, I'll share with the community.

**Comment by yehoshuadimarsky** [comment]
Thanks for your help, and especially the fast responses. Out of curiosity, why do you prefer having these discussions in a closed forum like Slack vs. an open forum like GitHub? If they are open, then users can search for them and you won't have to repeat yourself, among other benefits. 

Much of this idea comes from http://matthewrocklin.com/blog/2019/02/28/slack-github, but I wholeheartedly agree with his points.
