### ISSUE TITLE
Broken link from troubleshooting.md to async functions

### ISSUE THREAD

**Issue by tullo** [openfaas/docs#205]
The link in ` /deployment/troubleshooting.md`

Needs to be updated from:
`See also: [Reference: Asynchronous Functions](/reference/async)`
to:
`See also: [Reference: Asynchronous Functions](/docs/reference/async.md)`

**Comment by alexellis** [comment]
Thank you. Would you like to send a PR? Make sure you do it via the CLI and sign off the commit with git commit -s, thanks

**Comment by tullo** [comment]
Okay, will do so

**Comment by tullo** [comment]
Sorry @alexellis for bothering you again, but I just realized that the generated docs now have a failing link b/c of my pull request. So please rollback the merge again!

Somehow I did not see that I was supposed to test my changes with `docker run --rm -it -p 8000:8000 -v $(pwd):/docs squidfunk/mkdocs-material`

The change was a result from me following allong Lab7 and hitting the link which pointed to the markdown source file on github and made me come up with this issue https://github.com/openfaas/workshop/issues/169 report and pull request.

**Comment by alexellis** [comment]
I can't roll back, but you can send a PR to revert it. Please do test your changes properly next time as I took this on trust. Thanks 👍
