### ISSUE TITLE
Add documentation on how to deal with CORS and local development

### ISSUE THREAD

**Issue by kenfdev** [openfaas/docs#22]
Regarding to [this issue](https://github.com/openfaas/faas/issues/230#issuecomment-391626482), and talking with Alex, we could add documentation about how to deal with CORS when developing locally on SPAs (Single Page Applications).

* Explain CORS and why it may come up as a problem during local dev or production
* Explain about adding a proxy in front to make the caller think he's requesting the same domain
* Show a SPA app with Vue.js + webpack how to develop locally.

**Comment by kenfdev** [comment]
Derek assign: me

**Comment by alexellis** [comment]
🎉 merged
