### ISSUE TITLE
Document new max_inflight behaviour for NATS queue worker (async reference page)

### ISSUE THREAD

**Issue by alexellis** [openfaas/docs#225]
## Proposed change

Document new max_inflight behaviour for NATS queue worker (async reference page)

## Context

After https://github.com/openfaas/nats-queue-worker/pull/95 was merged, we need to update the documentation to explain that A) concurrency can now be controlled via this env-var and B) HA can be controlled by replicas.

We should also make the flag available in the [helm chart](https://github.com/openfaas/faas-netes/tree/master/chart/openfaas) if it is not already, and in the [CLI installer for OpenFaaS (arkade)](https://github.com/alexellis/arkade/blob/master/cmd/apps/openfaas_app.go)

**Comment by matthiashanel** [comment]
@alexellis will do. the pr came with a suggested doc change. were. you ok with that?

**Comment by matthiashanel** [comment]
Basically adding:
Alternatively you can increase the parallelism by setting "max_inflight" to a value greater than one. This will cause the queue-worker to concurrently receive up to max_inflight many messages and simultaneously invoke their corresponding functions. Should you wish to restrict concurrent invocation for certain functions, please make use of the queue feature and separate these from functions where you want more concurrency. When you scale up a queue worker, please be aware that you will get n * max_inflight parallel tasks.
