### ISSUE TITLE
Document how to use namespaces with faasd

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/docs#272]
## Proposed change

We should extend this page https://docs.openfaas.com/reference/namespaces/  to include two sections, one for faas-netes and one for faasd.

The faasd section needs to include instructions for how to create a new namespace, basically just this snippet

```sh
sudo ctr namespace create certifier-test
sudo ctr namespace label certifier-test openfaas=true
```

## Context

I realized that we had no documentation for namespace in faasd because i was trying to test something locally but failed because I forgot this setup step. I tried finding it in the faasd repo and then in the docs, but could not find it at all. If it exists, perhaps we need to make it easier to find. 

I found the required commands from the certifier CI test setup for faasd.

**Comment by LucasRoesler** [comment]
This should also document how to disable a namespace, currently this is the correct command

```sh
sudo ctr namespace label certifier-test openfaas
```

It might also be nice to have some instructions on how to correctly delete a namespace

**Comment by alexellis** [comment]
I've taken on the feedback and added this in a new sub-chapter in Serverless For Everyone Else, which is the official source for faasd documentation. Folks can also use the commands show above if they land here, or read the source code for faasd.
