### ISSUE TITLE
Deployment guide for Kubernetes missing steps cited in intro

### ISSUE THREAD

**Issue by zr-msft** [openfaas/docs#277]
The [Deployment guide for Kubernetes](https://docs.openfaas.com/deployment/kubernetes) calls out the following in [this section](https://docs.openfaas.com/deployment/kubernetes/#installing-openfaas-overview):

> Once you have a cluster, you can follow the detailed instructions on this page.
> 
> * Install the OpenFaaS CLI
> * Deploy OpenFaaS using arkade or Helm
> * Find your OpenFaaS gateway address
> * Retrieve your gateway credentials
> * Log in, deploy a function, and try out the UI.

After [Deploy OpenFaaS using arkade or Helm](https://docs.openfaas.com/deployment/kubernetes/#3-gitops-tooling), the next section is on training, skipping the last three steps.

## Proposed change
I think there should be headings that correspond to the remaining 3 steps that are not currently documented.

Also, I think _3) GitOps Tooling_ is at the wrong heading level and should be fixed as part of this proposed change.

## Context
I want to be able to use this guide for installing OpenFaaS on a Kubernetes, but the remaining steps are missing, and I have to search elsewhere to complete the installation.

I'm willing to create the PR with my proposed changes, but I wanted the community to weigh in first to ensure that I'm not missing something.

## Your Environment
The documentation website: https://docs.openfaas.com/deployment/kubernetes

**Comment by alexellis** [comment]
Seems fair. We have moved a lot of what you mentioned into the arkade CLI, so technically it's there and printed after installation or via `arkade info openfaas`

The free training also provides a much more comprehensive starting point.
