### ISSUE TITLE
Arkade download link is incorrect

### ISSUE THREAD

**Issue by magick93** [openfaas/docs#282]
## Proposed change
The link to download arkade is broken

## Context

See https://docs.openfaas.com/tutorials/local-kind-registry/#install-arkade

**Comment by magick93** [comment]
PR #281

**Comment by alexellis** [comment]
Thanks for the report, our contribution guide states that for typos an issue is the best course of action. Case in point, we couldn't accept your PR due to the lack of sign-off.
