### ISSUE TITLE
choas-fn command example from retries documentation fails.

### ISSUE THREAD

**Issue by welteki** [openfaas/docs#286]
## Proposed change

The second command for using the choas-fn described in the retries documentation fails.
<img width="706" alt="Screenshot 2022-05-13 at 10 21 58" src="https://user-images.githubusercontent.com/16267532/168242925-c9fd0024-3f55-4409-8955-e547228f1e08.png">

```
Error while reading configuration: no template repos currently configured
```
**option 1**:
Update the chaos-fn.yml in [alexellis/chaos-fn](https://github.com/alexellis/chaos-fn) to include:
```
configuration:
  templates:
    - name: golang-middleware
       source: https://github.com/openfaas/golang-http-template
```
**option 2**: replace command with `faas-cli template store pull golang-middleware`

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Thanks for the PR, in future if you add "Closes / Fixes: X" to your PR, it should close the linked issue for you.
