### ISSUE TITLE
Deploy example cmd in zero scale docs sets annotiation instead of label

### ISSUE THREAD

**Issue by welteki** [openfaas/docs#288]
## Proposed change

<img width="705" alt="Screenshot 2022-05-23 at 11 33 26" src="https://user-images.githubusercontent.com/16267532/169795236-9b8fab5b-b74a-4fac-a959-0cbf01279466.png">
This should be set as a label and not an annotation.

 - Update command to use `--label` flag.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Thank you Han. For these kinds of corrections I think we can skip the separate issue.
