### ISSUE TITLE
Typo in docs/reference/cron.md

### ISSUE THREAD

**Issue by RianM** [openfaas/docs#293]
#### Link:
https://github.com/openfaas/docs/blob/master/docs/reference/cron.md?plain=1#L62
#### Text:
> [Kubernetes][k8s] has its own [CronJob API resource][k8scron], which cam be used to schedule regularly function executions with a cron expression.

### Description:

1. "cam" should be "can"
2. "schedule regularly function executions" should be "schedule regular function executions"

**Comment by welteki** [comment]
Thanks for reporting this.

For future reference please just fill out the relevant fields in the provided issue template. A Pull Request is not necessary for typos.
