### ISSUE TITLE
Broken link at Installing OpenFaaS (overview) section

### ISSUE THREAD

**Issue by sstamatiadis** [openfaas/docs#302]
I found a broken link at [Installing OpenFaaS (overview)](https://docs.openfaas.com/deployment/kubernetes/#installing-openfaas-overview) under [Kubernetes Deployment guide](https://docs.openfaas.com/deployment/kubernetes/).

Link to line: https://github.com/openfaas/docs/blob/master/docs/deployment/kubernetes.md?plain=1#L11
Possible missing slash character.

## Proposed change
Repair broken link. Maybe it should be pointing to [https://docs.openfaas.com/architecture/stack/](https://docs.openfaas.com/architecture/stack/).

## Context
The aim is to improve doc and fix the broken link.

## Your Environment
N/A

**Comment by welteki** [comment]
Thanks for reporting this.

**Comment by sstamatiadis** [comment]
> Thanks for reporting this.

It is my pleasure to contribute. :)
