### ISSUE TITLE
Issue pulling function image from local (kinD) registry

### ISSUE THREAD

**Issue by fredericschulz** [openfaas/docs#334]
Hi everyone,

Right now im experimenting with OpenFaaS and am trying to setup everything locally, including the registry. For this I was basically following [this guide](https://docs.openfaas.com/tutorials/local-kind-registry/).
I'm on macOS and run an M1 chip if that is relevant.
A store function I can deploy and invoke without a problem. The custom (template) function that I deployed cannot be invoked as the function image cannot be pulled from the registry.

## How I set up:

I adapted the script for setting up and running the kinD registry so that the registry is running on port 5001 as the default port (5000) was already occupied on my mac. This is the script I ran for launching the registry:

```bash
#!/bin/sh
set -o errexit

# create registry container unless it already exists
reg_name='kind-registry'
reg_port='5001'
running="$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)"
if [ "${running}" != 'true' ]; then
  docker run \
    -d --restart=always -p "${reg_port}:5000" --name "${reg_name}" \
    registry:2
fi

# create a cluster with the local registry enabled in containerd
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
    endpoint = ["http://${reg_name}:${reg_port}"]
EOF

# connect the registry to the cluster network
docker network connect "kind" "${reg_name}"

# tell https://tilt.dev to use the registry
# https://docs.tilt.dev/choosing_clusters.html#discovering-the-registry
for node in $(kind get nodes); do
  kubectl annotate node "${node}" "kind.x-k8s.io/registry=localhost:${reg_port}";
done
```

Then I created a node template function by running `faas-cli new node-hello-world --lang node`.
I adapted the yaml file to specify the local registry on port 5001:
```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  node-hello-world:
    lang: node
    handler: ./node-hello-world
    image: localhost:5001/node-hello-world:latest
```

As per the guide I have set the `OPENFAAS_PREFIX` to `localhost:5001`. I have also tried setting it to the ip I get from `ifconfig` as the guide mentioned. 

Currently if I run `faas-cli up -f node-hello-world.yml` I get 
```
[0] > Pushing node-hello-world [localhost:5001/node-hello-world:latest]
The push refers to repository [localhost:5001/node-hello-world]
Get "http://localhost:5001/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2023/03/24 15:23:02 ERROR - Could not execute command: [docker push localhost:5001/node-hello-world:latest]
```

I was able to push before though, I do not know what broke, that makes it impossiblie to push now. Before and now I get the following output when running `kubectl get pod -n openfaas-fn`
```
NAME                                READY   STATUS             RESTARTS   AGE
figlet-85f9fdcff5-rlqt9             1/1     Running            0          13h
node-hello-world-5864bb554d-6ksgx   0/1     ImagePullBackOff   0          13h
```

From the documentation I cannot gather how to make my lokal registry accesible from openfaas.

## My Environment
* faas-cli version:
```
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  2fd284845648250484f03d126b383bdf99bd063d
 version: 0.16.1

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.26.3
 sha:     a128df471f406690b1021a32317340b29689c315


Provider
 name:          faas-netes-ce
 orchestration: kubernetes
 version:       0.16.6
 sha:           8cbe374a518893ec9f5d96071c1e7523834665b3
Your faas-cli version (0.16.1) may be out of date. Version: 0.16.2 is now available on GitHub.
```
* Docker version:
```
Client:
 Cloud integration: v1.0.31
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:35:19 2023
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.17.0 (99724)
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:31:28 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```
* I am using Kubernetes and installed openfaas via arkade. arkade version:
```
  __ _ _ __| | ____ _  __| | ___
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|

Open Source Marketplace For Developer Tools

Version: 0.9.5
Git Commit: 9ef881da4cd2038a33bf07d9d31d37f0397ff359

 🐳 arkade needs your support: https://github.com/sponsors/alexellis
```
* macOS version: `13.2 (22D49)`

I did also follow the troubleshooting guide but was only able to conclude that the imag may not be pulled.
Any help on solving this issue and maybe extend the documentation is much appreciated.

**Comment by alexellis** [comment]
Hi @fredericschulz, this is unfortunately outside of the scope of the kind of support we can offer to community members on a free and unpaid basis.

I'd suggest using a registry on your local network or deploying an in-cluster registry with a guide like this one:

https://blog.alexellis.io/get-a-tls-enabled-docker-registry-in-5-minutes/

You may also find the `faas-cli local-run` command makes more sense for rapid iteration than pushing into K8s and deploying via OpenFaaS.

The author of the tutorial is @yankeexe - I don't know if he has the bandwidth to support you here, but if so, I'm sure he'll reply.

https://dev.to/yankee/deploy-your-serverless-python-function-locally-with-openfaas-in-kubernetes-18jf

If you see anything important in the KinD docs (which is what @yankeexe adapted) then feel free to send a PR:

https://kind.sigs.k8s.io/docs/user/local-registry/

Alex

**Comment by alexellis** [comment]
I've gone ahead and done that for you.

If you are enjoying OpenFaaS, please [sponsor it via GitHub](https://github.com/sponsors/openfaas/) using a pre-defined or custom tier.
