### ISSUE TITLE
CE Install docs incorrectly say Function CRD is installed

### ISSUE THREAD

**Issue by bmarick** [openfaas/docs#348]
## Proposed change
Update the docs to say you need a pro license or remove that section of the docs.

## Context
Found this while trying to deploy a new instance of OpenFaaS CE, but the Function CRDs were not installed.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ): N/A
* Docker version `docker version` (e.g. Docker 17.0.05 ): v1.24.13
* Are you using Kubernetes or faasd? Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS): Linux

* Link to your project or a code example to reproduce issue: N/A

* Please also follow the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Thanks for the feedback. I've commented on the PR and we'll take a look into whether or how we'll change the wording.
