### ISSUE TITLE
Support question about secrets

### ISSUE THREAD

**Issue by vitaliyazvinski** [openfaas/docs#352]
According to documentation I was expecting to get access to a secret file in nodejs through `/var/lib/faasd-provider/secrets`, however it won't work.
## Proposed change

Instead of:
For faasd, secrets are created as plaintext files under `/var/lib/faasd-provider/secrets`. When you deploy a function, these secrets are bind-mounted into your container.

I found nodejs function working with:
For faasd, secrets are created as plaintext files under `/var/openfaas/secrets`. When you deploy a function, these secrets are bind-mounted into your container.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

CLI:
 commit:  d240045769678f0fa998e9311d4a81a89f0953d2
 version: 0.16.10

Gateway
 version: 0.27.0

Provider
 name:          faasd
 orchestration: containerd
 version:       0.18.1 

* Docker version `docker version` (e.g. Docker 17.0.05 ):

 Version:           24.0.6
 API version:       1.43
* Are you using Kubernetes or faasd?
 
faasd
* Operating System and version (e.g. Linux, Windows, MacOS):

linux
* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Hi @vitaliyazvinski I'm not sure what you're trying to say or what you'd like to happen here.

Everything is working as [documented in the handbook](https://store.openfaas.com/l/serverless-for-everyone-else?layout=profile), I can't see any issues here.

Can you clarify?

Alex

**Comment by vitaliyazvinski** [comment]
Hi @alexellis thank you for a quick reply.

In [docs](https://docs.openfaas.com/reference/secrets/) it's mentioned that secrets for faasd are located under `/var/lib/faasd-provider/secrets`, however it's not possible to get them in function by that path. Physically they indeed located there but as far as I can see they are "mounted" to container under `/var/openfaas/secrets`. My suggestion was to update the documentation accordingly.
My steps:
1. I generated a token:
`echo $(head -c 16 /dev/urandom |shasum |cut -d "-" -f1) > token.txt`
2. I created a secret:
`faas-cli secret create private-api-token --from-file token.txt`
3. echo.yml:
```
version: 1.0
provider:
  name: openfaas
  gateway: [reducted]
functions:
  echo:
    lang: node18
    handler: ./echo
    image: [reducted]
    secrets:
      - private-api-token
```
4. js code to get a token:
```
token = await fs.readFile(
  "/var/lib/faasd-provider/secrets/private-api-token",
  "utf8",
);
```
5. build & deploy: `faas-cli up -f ./echo.yml -g https://reducted`

6. invoke: `curl --location 'https://[reducted]/function/echo' \
--header 'Authorization: Bearer [reducted]'`

Result by `journalctl -t openfaas-fn:echo -r`:
```
Oct 20 12:51:57 faasd openfaas-fn:echo[28490]: ENOENT: no such file or directory, open '/var/lib/faasd-provider/secrets/private-api-token'
```

If I change a path in step 4 to `/var/openfaas/secrets/private-api-token` it works.

**Comment by vitaliyazvinski** [comment]
@alexellis 
I've reread the page I linked to and yes, it was my fault that I got confused about it since I was quickly scanning the page and found `faasd` with path details.
I'm closing a thread, no changes are needed.
Thank you.

**Comment by alexellis** [comment]
The text `/var/lib/faasd-provider/secrets/private-api-token` is not contained within my eBook, so I'm not sure what you would like me to change in the eBook to improve it. Can you clarify?

If you're finding faasd to be of value, and want to support our continued work on it, you can [sponsor OpenFaaS via GitHub](https://github.com/sponsors/openfaas)
