### ISSUE TITLE
Document --filter and --parallel for build and push

### ISSUE THREAD

**Issue by alexellis** [openfaas/docs#38]
The new build docs page in #32 is very sparse, it should cover some of the advanced feature of the `build` command such as `--filter` and `--parallel` - these are essential for working with larger stacks.

**Comment by rgee0** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Just sent a new invitation, please join again and thanks for picking this task up.

**Comment by rgee0** [comment]
Derek assign: me

**Comment by ericstoekl** [comment]
Document `--regex` while you're at it?

**Comment by alexellis** [comment]
Thanks for taking this Richard. Maybe add it to Trello to show work-in-progress?

**Comment by rgee0** [comment]
Adding `--sign` and `--key` from openfaas/faas-cli#530 to the scope for this

**Comment by alexellis** [comment]
@rgee0 please can you review this issue / progress and if necessary find someone to pick it up?
