### ISSUE TITLE
Copy function on the docs site code boxes includes $ character

### ISSUE THREAD

**Issue by rgee0** [openfaas/docs#44]
The button to copy from code blocks on the docs pages also copies the $ symbol.

Should the $ suffix be dropped now that the .md files are generating the docs site?
Does the docs generation process make it possible to strip the leading $?

**Comment by alexellis** [comment]
The $ symbol is there to show the difference between a command to be typed in and output from said command(s). You'll see similar in the Docker docs. I don't know if their copy button strips the $ character?

Alex

**Comment by rgee0** [comment]
I understand why its there, it does render the copy button somewhat pointless, however.  As do the code blocks with both the command to be entered and the expected response - the whole lot gets copied.

Im not sure Docker offer a copy button on their code blocks.

**Comment by jonatasbaldin** [comment]
Also the copy button copies the whole block, including the output.

One nice way would be to have a copy button that strips the `$` off and the output, but I think it's just a nice to have 😅
