### ISSUE TITLE
Document --tag flag and how it works

### ISSUE THREAD

**Issue by alexellis** [openfaas/docs#49]
Find a place in the CLI docs to document how the --tag flag works.

Remember this covers build/push and deploy - do we really want to duplicate the text in each part - or could it be a sub-page of the CLI heading?

https://github.com/openfaas/faas-cli/pull/465

**Comment by alexellis** [comment]
@mrtind do you want to take a shot at this? We can review the wording and guide some guidance after the technical parts are in? You'll find instructions in the README for how to test locally.

**Comment by mrtind** [comment]
Yeah I'm on it.
