### ISSUE TITLE
Include interesting repositories from OpenFaaS-Incubator in Get Started page

### ISSUE THREAD

**Issue by bartsmykla** [openfaas/docs#73]
We want to include the most interesting repositories from OpenFaas Incubator in [Get started](https://docs.openfaas.com/contributing/get-started/) as a table with link and short description (like currently [OpenFaas](https://docs.openfaas.com/contributing/get-started/#openfaas)).

At the beginning I suggest to put there: [of-watchdog](https://github.com/openfaas-incubator/of-watchdog) and [faas-idler](https://github.com/openfaas-incubator/faas-idler) but feel free to add another suggestions! :-)

**Comment by alexellis** [comment]
Missed a key one! The Operator.. @stefanprodan I've added this now.

@openfaas/faas-team any others we are missing but need?

**Comment by ivanayov** [comment]
+1 for this
People asked if OpenFaaS can be integrated with Kafka, so I’d suggest including the kafka-connector as well.

**Comment by alexellis** [comment]
Kafka is already mentioned in the docs under the triggers page, but please do add the link here too.
