### ISSUE TITLE
Lower camel case secret name causes error

### ISSUE THREAD

**Issue by rgee0** [openfaas/docs#76]
This section:

https://github.com/openfaas/docs/blob/master/docs/deployment/kubernetes.md#link-the-image-pull-secret-to-a-namespace-service-account

Suggests the secret name to be used should be `myPrivateRepo`.  This causes the following error:

_The Secret "myPrivateRepo" is invalid: metadata.name: Invalid value: "myPrivateRepo": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')_

Suggest we move to a hypenated all lower case value.

**Comment by alexellis** [comment]
Sounds good to me. Any references in the FaaS repo?

**Comment by rgee0** [comment]
Not obvious from a search.  Found this one linked from the OFC repo.

+1 for linking where possible
