### ISSUE TITLE
Add additional CLI YAML attributes to reference section

### ISSUE THREAD

**Issue by rgee0** [openfaas/docs#80]
Currently the YAML section at https://docs.openfaas.com/reference/yaml/ is fairly complete, however it misses some of the more recent features:

- build_options
- readonly_root_filesystem
- skip_build

**Comment by rgee0** [comment]
Derek add label: Enhancement

**Comment by alexellis** [comment]
Bumping for @rgee0 / @martindekov or @LucasRoesler

**Comment by LucasRoesler** [comment]
Derek assign: me
